### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by Kasper888** [elpsychris/EmoRecogDemo#2]
The below line raising compile error, Kindly fix.

https://github.com/elpsychris/EmoRecogDemo/commit/0d93ac1fb3e49de9fa1ff4af65a5b3444421209f#r30890245

**Comment by elpsychris** [comment]
This project is still in developing phrase, there are many bugs appeared from the updates of the dependencies, because of the time limit of my assignment it has been put on-hold.

I wrote a new complete project in Python in the end. 

Check it out if you like [here](https://mega.nz/#F!3cFFjCiI!K1UpbJt0XD30BOVcaW5WeA)

I am deeply sorry. I might try to fix and make it run in the near future in my free time, hopefully.
